# Introduction to BeautifulSoup: Parsing and navigating HTML

# BeautifulSoup - it's your specialized tool for deciphering the language of the web.
# Specifically designed to parse HTML and XML documents
# transforms the often-chaotic structure of web pages into a neatly organized tree-like representation

# BeautifulSoup is incredibly flexible:
# allows you to read data from web pages as well as modify it 

# Core concepts and functions
# BeautifulSoup operates on a few fundamental concepts that form the foundation of its capabilities

# first step in working with BeautifulSoup is parsing:
# where an HTML or XML document is transformed into a structured, tree-like representation
# This structured representation allows BeautifulSoup to efficiently navigate and manipulate the document

# BeautifulSoup provides powerful search capabilities
# allowing you to pinpoint elements based on their attributes, content, 
# or even their relationship with other elements

# You can update existing content, remove unwanted elements, or even create entirely new HTML structures

# Methods of BeautifulSoup
# find() - retrieves the first occurrence of a specified tag or element
# find_all() - retrieves all occurrences of a specified tag or element, returning them as a list

# NOTE: class_ is used as a parameter name to denote a class object

# the select() function lets you leverage the power of CSS selectors, 
# the same language used to style web pages, providing pinpoint accuracy.
# get_text() extracts its pure text content, stripping away any HTML tags and leaving you with just the information you need. 
# attrs property serves as a convenient dictionary-like interface for accessing an element's attributes, such as its class, id, or href.


from bs4 import BeautifulSoup

# Sample HTML content (replace with your actual HTML)
html_content = """
<html>
<body>
    <h1>This is a heading</h1>
    <p>This is a paragraph.</p>
    <p class="special">This is another paragraph.</p>
</body>
</html>
"""

# Parse the HTML
soup = BeautifulSoup(html_content, 'html.parser')

# Find the first 'p' element
first_paragraph = soup.find('p')
print(first_paragraph)  # Output: <p>This is a paragraph.</p>

# Find all 'p' elements
all_paragraphs = soup.find_all('p')
for paragraph in all_paragraphs:
    print(paragraph)

# Find the 'p' element with the class 'special'
special_paragraph = soup.find('p', class_='special')

print(special_paragraph)  # Output: <p class="special">This is another paragraph.</p>

# from bs4 import BeautifulSoup

# Sample HTML content (replace with your actual HTML)
html_content = """
<html>
<body>
    <div id="main-content">
        <h1>This is a heading</h1>
        <p class="important">This is an important paragraph.</p>
        <a href="https://www.example.com">Visit Example</a>
    </div>
</body>
</html>
"""

# Parse the HTML
soup = BeautifulSoup(html_content, 'html.parser')

# Use CSS selector to find the 'div' with id 'main-content'
main_content = soup.select_one('#main-content')

# Find the 'p' element with class 'important' within 'main-content'
important_paragraph = main_content.select_one('.important')

# Extract the text content of the paragraph
paragraph_text = important_paragraph.get_text()
print(paragraph_text)  # Output: This is an important paragraph.

# Find the 'a' element within 'main-content'
link = main_content.select_one('a')

# Access the 'href' attribute of the link
link_url = link['href']
print(link_url)  # Output: https://www.example.com


# REAL LIFE APPLICATIONS 

# Web scraping - the automated extraction of data from websites, is perhaps the most prominent use case for BeautifulSoup
# market researcher tasked with tracking product prices across multiple e-commerce platforms
# You could write a script that uses BeautifulSoup to scrape product listings, extract prices, and store them in a database for analysis. 
# This would allow you to monitor price fluctuations and make informed decisions based on real-time data.

# Data cleaning and transformation
# Inconsistent HTML tags, formatting errors, and extraneous information can hinder data analysis and visualization
# BeautifulSoup acts as a powerful tool for cleaning and transforming this raw data into a more usable format.
# A data scientist might use BeautifulSoup to parse and clean HTML reports generated by a web application, 
# extracting relevant metrics and converting them into a structured format for further analysis.

# Content aggregation
# BeautifulSoup can be leveraged to aggregate content from multiple web pages into a single, centralized location
# A news aggregator could use BeautifulSoup to scrape articles from various news websites,
# extracting headlines, summaries, and publication dates, and then compiling them into a unified feed 
# for users to access the latest news from different sources in one place.

# Navigating the challenges of web scraping 
# Websites are constantly evolving
# This can potentially break BeautifulSoup scripts that rely on specific elements or patterns in the HTML
# It's crucial to test and maintain your code to ensure it continues to function as expected.

# Secondly, web scraping should always be conducted ethically and responsibly
# Always respect the website's terms of service and any restrictions outlined in their robots.txt file.

# BeautifulSoup's primary focus is on parsing static HTML.
# it might face limitations when dealing with dynamic content
# BeautifulSoup might not be able to access the full content unless you combine it with other tools or techniques that can render JavaScript and simulate user interactions.

# CODING CHALLENGE: EXTRACT PRODUCT INFORMATION

from bs4 import BeautifulSoup

html_content = """
<div class="product">
  <h1>Awesome Headphones</h1>
  <p class="price">$99.99</p>
  <p class="description">These headphones offer amazing sound quality!</p>
</div>
"""

soup = BeautifulSoup(html_content, 'html.parser')

# Use soup.find() to locate the <h1> tag and store the extracted text in a variable called 'product_name'.
product_name = soup.find('h1').get_text()

# Use soup.find() to locate <p> tags with class_='price' and store the extracted text in a variable called 'price'.
price = soup.find('p', class_='price').get_text()

# Use soup.find() to locate <p> tags with class_='description' and store the extracted text in a variable called 'description'.
description = soup.find('p', class_='description').get_text()

# Print the extracted data in the format:
print(f"Product name: {product_name}")
print(f"Price: {price}")
print(f"Description: {description}") 
